name: pico_log
version: 0.1.0
description: A tiny library for logger configuration.
author: mockturtl
#homepage: https://mockturtl.github.io/pico_log
dependencies:
  ansicolor: '^0.0.9'
  logging: '^0.9.0'
