name: pico_log
version: 0.2.0-beta.6+1
description: A tiny library for logger configuration.
author: mockturtl <mockturtl@gmail.com>
homepage: https://github.com/mockturtl/pico_log
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  ansicolor: '^0.0.9'
  logging: '^0.11.0'
