name: pico_log
version: 0.3.1+3
description: A tiny library for logger configuration.
author: mockturtl <mockturtl@gmail.com>
homepage: https://github.com/mockturtl/pico_log
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  ansicolor: ^0.0.9
  args: ^0.13.0
  logging: ^0.11.0
dev_dependencies:
  test: any
